server:
  port: 8080
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/goods?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 389894467
   redis:
      database: 0
      password: 389894467
      host: localhost
      port: 6379
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.szhua.goods.goods.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-underline: true
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false